let dataObject = {
    dances : [
        {
          name: `Bachata` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'GY2fE5xr6XU',
          short:"If you're looking to heat up the dance floor, then look no further than social bachata dancing! This sensual and passionate dance originated in the Dominican Republic and has since spread around the world, capturing the hearts of dancers everywhere with its smooth, rhythmic footwork and tantalizing body rolls. Whether you're a seasoned dancer or a beginner, social bachata is a great way to get moving and have fun. Plus, with its focus on connection and lead-and-follow techniques, it's a great way to build trust and chemistry with your dance partner. So put on your dancing shoes and get ready to sizzle with social bachata!",
          poem:"The bachata is a dance of passion and fire,<br>A fiery rhythm that never seems to tire.<br>With steps full of sensuality and flair,<br>It is a dance that truly doesn't compare.<br><br>From the Dominican Republic it hails,<br>A dance that never fails to make the heart quail.<br>With a style all its own, it's hard to resist,<br>The bachata is a dance that you can't miss.<br><br>So let's take to the floor, let our bodies move,<br>To the sound of the bachata, let's find our groove.<br>A dance of love, of desire and passion,<br>The bachata is a dance that will always be in fashion.",
          songs:[{ title:'"Amarte" by Romeo Santos',
                   link:'2W-KDtG3rx0'},
                   { title:'"Obsesión" by Aventura',
                   link:'SEjw5rdyvVg'},
                   { title:'"Bachata en Fukuoka" by Juan Luis Guerra',
                   link:'_4NBD3SqBwg'}, 
                   { title:'"Stand By Me" by Prince Royce',
                   link:'PPgQ4nDLh0s'},
                   { title:'"Darte un Beso" by Prince Royce',
                   link:'bdOXnTbyk0g'},
                   { title:'"Bonita " by Joss Favela',
                   link:'XwedmfsZdLE'},
                   { title:'"Como Duele" by Romeo Santos',
                   link:'fRybTC_xWGg'},
                   { title:'"Bachata Heightz" by Quiero Amarte',
                   link:'gvN0sgKfe3Y'},
                   { title:'"Me Va a Extrañar" by Luis Miguel Del Amargue',
                   link:'fmhpPE40Dqk'},            
                  ]
        },
        {
          name: `Cha Cha Cha` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'QWdbANbPaw4',
          short:"A fun, exciting, sassy dance that can be danced to both traditional Latin and new popular club music. As you cha cha across the dance floor, you'll feel the music pulse through your veins and bring a sense of joy and freedom to your body. The cha cha is all about having fun and expressing yourself through movement, and it's a great way to let go of any stress or inhibitions. Whether you're dancing solo or with a partner, the cha cha is a dance that allows you to connect with the music and let your inner dancer shine. So if you're ready to get your cha cha on, grab a partner and hit the dance floor! You won't be able to resist the allure of this exciting and infectious dance.",
          poem:"The Cha-Cha-Cha will add some fun to life,<br>Its music is catchy so you won't feel strife,<br>The rhythm is contagious and the moves pretty neat,<br>It'll make your heart beat at an upbeat!<br><br>The Cha-Cha-Cha is great for two to dance,<br>A way to get close and forget those glance,<br>The energy and spirit it brings is divine,<br>And the experience is worth a lifetime.<br><br>So come on, put on your dancing shoes,<br>And put on a show that no one can refuse,<br>Let the Cha-Cha-Cha enthuse you today,<br>And make you dance away in a joyous array!",
          songs:[{ title:'"Havana" by Camila Cabello',
                   link:'HCjNJDNzw8Y'},
                   { title:'"Smooth" by Santana ft. Rob Thomas ',
                   link:'6Whgn_iE5uc'}, 
                   { title:'"I Need to Know" by Marc Anthony',
                   link:'fLVzw9wVd9o'},
                   { title:'"Dance Again" by Jennifer Lopez ft. Pitbull',
                   link:'bjgFH01k0gU'},
                   { title:'"They’re Playin’ Our Song" by Neil McCoy',
                   link:'mKsEt4mJhDU'},
                   { title:'"If It Feels Good" (Then It Must Be) by Leon Bridges',
                   link:'WY6tIQOQcY0'},
                   { title:'"Sometimes She Forgets" · Steve Earle',
                   link:'kJCEjVLG5aU'},
                   { title:'“Cherry Pink and Apple Blossom White” by Perez Prado ',
                   link:'ec2SizWdP6o'},
                   { title:'"Smooth" by Santana featuring Rob Thomas',
                   link:'6Whgn_iE5uc'},
                   { title:'"24K Magic" by Bruno Mars',
                   link:'UqyT8IEBkvY'},        
                  ] 
        },
        {
          name: `Foxtrot` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'tAZ-38F-G74',
          short:'The social foxtrot is a dance that exudes elegance and grace. As you glide across the dance floor, the smooth, flowing movements of the foxtrot will transport you to a world of sophisticated glamour. Whether you are a seasoned dancer or a beginner looking to learn something new, the foxtrot is a fantastic choice. With its mix of quick and slow steps, the foxtrot is both challenging and rewarding to dance. So put on your dancing shoes and let the social foxtrot sweep you off your feet!',
          poem:"Let's step out and have a ball,<br>Do the foxtrot, one and all,<br>Move your feet so fast and light,<br>To the music, take flight.<br><br>Do a rhythm all your own,<br>Gracefully you'll be shown,<br>Glide along to the beat,<br>A happy, joyous feat.<br><br>Slide to the left, slide to the right,<br>Smiling faces beaming bright,<br>Create a new and exciting show,<br>Foxtrot is the dance you should know.",
          songs:[{ title:'“Thinking Out Loud” by Ed Sheeran',
                   link:'lp-EO5I60KA'},
                   { title:'“All of Me” by John Legend',
                   link:'ngq5Aw0Q6rQ'}, 
                   { title:'“Fly Me to the Moon” by Frank Sinatra',
                   link:'ZEcqHA7dbwM'},
                   { title:'“I Don’t Want to Miss a Thing” by Aerosmith',
                   link:'JkK8g6FMEXE'},
                   { title:'“You Are the Best Thing” by Ray LaMontagne',
                   link:'pkntWssHboY'},
                   { title:'LOVE - The Swing Cats',
                   link:'DBCA8_RC3So'},
                   { title:'“Unforgettable” by Nat King Cole',
                   link:'-XDAnPvTQFo'},
                   { title:'“The Nearness of You” by Norah Jone',
                   link:'hsczuCzyUs4'},
                   { title:'“I’ve Got You Under My Skin” by Michael Bublé',
                   link:'SMjex7AfTsg'},
                   { title:'“It Had to Be You” by Harry Connick Jr.',
                   link:'_UnQOfPwZfs'},             
                  ]
        },
        {
          name: `Rumba` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'ZCaLLyjZgX4',
          short:'Short text4.',
          poem:"Under a moonlit sky, passion ignites,<br>Two souls entwined in warm Rumba nights.<br>Steps with rhythm, hearts in tune,<br>A dance of love, beneath the moon.<br><br>Sensual sways and fiery moves,<br>Every step, our love approves.<br>Hand in hand, cheek to cheek,<br>In Rumba's heat, emotions peak.<br><br>Whispers of love in every glide,<br>As we dance, side by side.<br>With every turn, our bond grows stronger,<br>In this dance, love will linger longer.<br><br>Rumba’s fire, burning bright,<br>A dance of passion, pure delight.<br>In each movement, our love blooms,<br>As we Rumba, through life's rooms.",
          songs:[{ title:'“Love on the Brain” by Rihanna',
                   link:'nyxKQYWaWOg'},
                   { title:'“Say You Won’t Let Go” by James Arthur',
                   link:'0yW7w8F2TVA'}, 
                   { title:'“Perfect” by Ed Sheeran',
                   link:'kPhpHvnnn0Q'},
                   { title:'“I Will Always Love You” by Whitney Houston',
                   link:'3JWTaaS7LdU'},
                   { title:'“When I Fall in Love” by Nat King Cole',
                   link:'GfAb0gNPy6s'},
                   { title:'“I’m Yours” by Jason Mraz',
                   link:'EkHTsc9PU2A'},
                   { title:'“You Are the Reason” by Calum Scott',
                   link:'ShZ978fBl6Y'},
                   { title:'“I’ll Be There for You” by Bon Jovi',
                   link:'-fj2NRooVRk'}, 
                   { title:'“Just the Way You Are” by Bruno Mars',
                   link:'LjhCEhWiKXk'},
                   { title:'“Have I told you lately” by Rod Stewart',
                   link:'3z-gpMVnnao'},            
                  ]
        },
     
        {
          name: `Slow Waltz` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'6flHn0wCR64',
          short:'The wedding waltz is a dance of intimate connection and fluid elegance, where the couple’s love takes center stage in a series of sweeping, graceful movements, creating a timeless moment on their special day. ',
          poem:"On a day when love's light shimmers bright,<br>Two hearts entwined in gentle flight.<br>Slow Waltz, the dance of timeless grace,<br>Where each step paints love's embrace.<br><br>In your arms, we glide so near,<br> Every moment crystal clear.<br>Rhythms whisper, soft and low,<br>In elegant steps, our love will grow.<br><br>Swaying slowly, heart to heart,<br>From this dance, we'll never part.<br>As we waltz through life anew,<br>Let this be our vow, our view.<br><br>In the dance of love, we find,<br>A memory, forever kind.<br>Slow Waltz, our romantic art,<br>Echoes of our unified heart.",
          songs:[{ title:'"Moon River" by Andy Williams (Featured in Breakfast at Tiffany’s)',
                   link:'L_jgIezosVA'},
                   { title:'"Unchained Melody" by The Righteous Brothers (Iconic in Ghost)',
                   link:'Zv8czIoAw5w'}, 
                   { title:'"Can’t Help Falling in Love" by Elvis Presley (Romantic highlight in Blue Hawaii)',
                   link:'vGJTaP6anOU'},
                   { title:'"Come Away With Me" by Norah Jones',
                   link:'lbjZPFBD6JU'},
                   { title:'"La Vie En Rose" by Laura Fygi',
                   link:'o7_DbwxwAJQ'},
                   { title:'"It Is You (I Have Loved)" by Dana Glover (From the enchanting world of Shrek)',
                   link:'hs6hGYyq-vc'},
                   { title:'"Can You Feel The Love Tonight" by Elton John (Brings the magic of The Lion King to your dance floor)',
                   link:'c56IJWgrkNE'},
                   { title:'“You’ve Got The Heart Of A Star” by Oasis',
                   link:'gwPCBL0-zDc'}, 
                   { title:'"Open Arms" by Celine Dion',
                   link:'c3l0FiWgb-Q'},
                   { title:'"Always remember us this way" by Lady Gaga',
                   link:'p1godKRBeZc'},            
                  ]
        },
        {
          name: `Swing` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'OJ5SGojIHbs',
          short:'Short text4.',
          poem:"In a world of rhythm, fast and bright,<br>Two hearts leap in swing's delight.<br>Bouncing steps and laughter clear,<br>In swing's embrace, love draws near.<br><br>Jumps and turns with joyful flair,<br>Hand in hand, we pair the air.<br>In each move, our spirits lift,<br>Swing's the dance that gives love a gift.<br><br>Happy feet in sync, we glide,<br>With every beat, love amplified.<br>In this dance, our joy explodes,<br>Swing's the rhythm where love unfolds.<br><br>Together, we create a scene,<br>With swing's energy, our love is seen.<br>In every twirl, our hearts sing,<br>As we dance through life, in joyous swing.",
          songs:[{ title:'“Feel So Close” by Calvin Harris',
                   link:'dGghkjpNCQ8'},
                   { title:'“Ex’s & Oh’s” by Elle King',
                   link:'X9OvgrxaPKU'},  
                   { title:'Neil Young by Harvest Moon',
                   link:'n2MtEsrcTTs'},
                   { title:'"Crazy Little Thing Called Love" by Queen',
                   link:'zO6D_BAuYCI'},
                   { title:'"Hallelujah I Love Her So" by Ray Charles',
                   link:'v-JsqKlVVGk'},
                   { title:'“Budapest” by George Ezra',
                   link:'VHrLPs3_1Fs'}, 
                   { title:'“Dear Future Husband” by Meghan Trainor',
                   link:'ShlW5plD_40'},
                   { title:'“In The Mood” by The Andrews Sisters',
                   link:'gOuLfqLS5Mc'}, 
                    { title:'“Just the Way You Are” by Bruno Mars',
                   link:'LjhCEhWiKXk'},
                   { title:'“Zoot Suit Riot” by Cherry Poppin’ Daddies',
                   link:'JZm1krVKzBY'},        
                  ]
        },
        {
          name: `Tango` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'G3h2pxNLQ-Q',
          short:'The Tango, a passionate and dramatic dance, is an expression of deep connection and fiery love, making it a captivating choice for a wedding dance that leaves a lasting impression of the couple’s intense bond.',
          poem:"In a world where passion ignites the flame,<br>Two lovers dance, in tango’s name.<br>With every step, intensity grows,<br>In each other's arms, the dance flows.<br><br>Sharp and smooth, a blend so fine,<br>Entwined in rhythm, hearts align.<br>Eyes that lock, movements bold,<br>In tango's embrace, stories are told.<br><br>With a flick and a twirl, love's allure,<br>A timeless dance, emotions pure.<br>With every turn, the connection deep,<br>In tango's grasp, our hearts leap.<br><br>In this dance of passion and fire,<br>We find our love, our true desire.<br>Tango’s steps, a love song played,<br>As we dance, our vows conveyed.",
          songs:[{ title:'"Querer" by Francesca Gagnon',
                   link:'01WukohheHQ'},
                   { title:'"Kiss of Fire" by Georgia Gibbs',
                   link:'mLpzfER6w3c'}, 
                   { title:'"Por Una Cabeza" by Carlos Gardel',
                   link:'s-AV3c5Ygvs'},
                   { title:'"The Weddingbell Tango" by Alfred Hause Orchestra',
                   link:'f9jDK9pR_uA'},
                   { title:'"Blue Tango" by Leroy Anderson',
                   link:'0YEsJpKsbBU'},
                   { title:'"La Cumparsita" by Julio Iglesias',
                   link:'GrzlLVO_tBY'},
                   { title:'"Castle on the Hill" by Ed Sheeran',
                   link:'K0ibBPhiaG0'},
                   { title:'"Hold Back The River" by James Bay',
                   link:'mqiH0ZSkM9I'}, 
                   { title:'"Whatever It Takes" by Imagine Dragons',
                   link:'gOsM-DYAEhY'},
                   { title:'"Jungle" by X Ambassadors, Jamie N Commons',
                   link:'aqXW57WM9TA'},            
                  ]
        },
        {
          name: `Viennese Waltz` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'-LLzvce0joI',
          short:'Short text4.',
          poem:"In a swirl of elegance, where dreams alight,<br>Two hearts dance, in Viennese Waltz's light.<br>Graceful spins, a seamless flow,<br>In perfect harmony, love’s glow.<br><br>Swiftly moving, hand in hand,<br>Through the ballroom, we grandly stand.<br>Every turn, our love conveyed,<br>In Viennese Waltz, memories made.<br><br>With each twirl, we feel the breeze,<br>A dance of ease, our hearts appease.<br>In every step, a silent vow,<br>In this waltz, love we avow.<br><br>As we glide through life's grand hall,<br>The Viennese Waltz, we recall.<br>In this dance, our love’s romance,<br>A timeless, elegant wedding dance.",
          songs:[{ title:'“A Thousand Years” by Christina Perri',
                   link:'mk3XycambgI'},
                   { title:'“Can’t Help Falling in Love” by Elvis Presley',
                   link:'vGJTaP6anOU'}, 
                   { title:'"Perfect" by Ed Sheeran',
                   link:'c8ivQ5qM-uA'},
                   { title:'"Nothing Else Matters" by Metallica',
                   link:'Fkj6-LN6WKI'},
                   { title:'"Fallin’" by Alicia Keys',
                   link:'Urdlvw0SSEc'},
                   { title:'"Kiss From A Rose" by Seal',
                   link:'3-Yh6rnOchs'},
                   { title:'"Iris" by Goo Goo Dolls',
                   link:'NdYWuo9OFAw'},
                   { title:'"Waltz of the Flowers" by Tchaikovsky (The Nutcracker)',
                   link:'LKcZL8q1eBw'}, 
                   { title:'"A Ti Korita Vu" by Angel of Wishes - Sanavè',
                   link:'_MLSDm8gtsM'},
                   { title:'"Waltz No.2" by Dmitri Shostakovich',
                   link:'WaKdPgkTZ7M'}
                  ]
        },
              ],
     
  };
  
  export default dataObject;
 
