let dataObject = {
    dances : [
        {
          name: `Bachata` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'GY2fE5xr6XU',
          short:"If you're looking to heat up the dance floor, then look no further than social bachata dancing! This sensual and passionate dance originated in the Dominican Republic and has since spread around the world, capturing the hearts of dancers everywhere with its smooth, rhythmic footwork and tantalizing body rolls. Whether you're a seasoned dancer or a beginner, social bachata is a great way to get moving and have fun. Plus, with its focus on connection and lead-and-follow techniques, it's a great way to build trust and chemistry with your dance partner. So put on your dancing shoes and get ready to sizzle with social bachata!",
          poem:"The bachata is a dance of passion and fire,<br>A fiery rhythm that never seems to tire.<br>With steps full of sensuality and flair,<br>It is a dance that truly doesn't compare.<br><br>From the Dominican Republic it hails,<br>A dance that never fails to make the heart quail.<br>With a style all its own, it's hard to resist,<br>The bachata is a dance that you can't miss.<br><br>So let's take to the floor, let our bodies move,<br>To the sound of the bachata, let's find our groove.<br>A dance of love, of desire and passion,<br>The bachata is a dance that will always be in fashion.",
          songs:[{ title:'"Amarte" by Romeo Santos',
                   link:'2W-KDtG3rx0'},
                   { title:'"Obsesión" by Aventura',
                   link:'SEjw5rdyvVg'},
                   { title:'"Bachata en Fukuoka" by Juan Luis Guerra',
                   link:'_4NBD3SqBwg'}, 
                   { title:'"Stand By Me" by Prince Royce',
                   link:'PPgQ4nDLh0s'},
                   { title:'"Darte un Beso" by Prince Royce',
                   link:'bdOXnTbyk0g'},
                   { title:'"Bonita " by Joss Favela',
                   link:'XwedmfsZdLE'},
                   { title:'"Como Duele" by Romeo Santos',
                   link:'fRybTC_xWGg'},
                   { title:'"Bachata Heightz" by Quiero Amarte',
                   link:'gvN0sgKfe3Y'},
                   { title:'"Me Va a Extrañar" by Luis Miguel Del Amargue',
                   link:'fmhpPE40Dqk'},            
                  ]
        },
        {
          name: `Cha Cha Cha` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'https://youtube.com',
          short:"A fun, exciting, sassy dance that can be danced to both traditional Latin and new popular club music. As you cha cha across the dance floor, you'll feel the music pulse through your veins and bring a sense of joy and freedom to your body. The cha cha is all about having fun and expressing yourself through movement, and it's a great way to let go of any stress or inhibitions. Whether you're dancing solo or with a partner, the cha cha is a dance that allows you to connect with the music and let your inner dancer shine. So if you're ready to get your cha cha on, grab a partner and hit the dance floor! You won't be able to resist the allure of this exciting and infectious dance.",
          poem:"The Cha-Cha-Cha will add some fun to life,<br>Its music is catchy so you won't feel strife,<br>The rhythm is contagious and the moves pretty neat,<br>It'll make your heart beat at an upbeat!<br><br>The Cha-Cha-Cha is great for two to dance,<br>A way to get close and forget those glance,<br>The energy and spirit it brings is divine,<br>And the experience is worth a lifetime.<br><br>So come on, put on your dancing shoes,<br>And put on a show that no one can refuse,<br>Let the Cha-Cha-Cha enthuse you today,<br>And make you dance away in a joyous array!",
          songs:[{ title:'"Havana" by Camila Cabello',
                   link:'HCjNJDNzw8Y'},
                   { title:'"Smooth" by Santana ft. Rob Thomas ',
                   link:'6Whgn_iE5uc'}, 
                   { title:'"I Need to Know" by Marc Anthony',
                   link:'fLVzw9wVd9o'},
                   { title:'"Dance Again" by Jennifer Lopez ft. Pitbull',
                   link:'bjgFH01k0gU'},
                   { title:'"They’re Playin’ Our Song" by Neil McCoy',
                   link:'mKsEt4mJhDU'},
                   { title:'"If It Feels Good" (Then It Must Be) by Leon Bridges',
                   link:'WY6tIQOQcY0'},
                   { title:'"Sometimes She Forgets" · Steve Earle',
                   link:'kJCEjVLG5aU'},
                   { title:'“Cherry Pink and Apple Blossom White” by Perez Prado ',
                   link:'ec2SizWdP6o'},            
                  ]
        },
        {
          name: `Foxtrot` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'https://youtube.com',
          short:'The social foxtrot is a dance that exudes elegance and grace. As you glide across the dance floor, the smooth, flowing movements of the foxtrot will transport you to a world of sophisticated glamour. Whether you are a seasoned dancer or a beginner looking to learn something new, the foxtrot is a fantastic choice. With its mix of quick and slow steps, the foxtrot is both challenging and rewarding to dance. So put on your dancing shoes and let the social foxtrot sweep you off your feet!',
          poem:"Let's step out and have a ball,<br>Do the foxtrot, one and all,<br>Move your feet so fast and light,<br>To the music, take flight.<br><br>Do a rhythm all your own,<br>Gracefully you'll be shown,<br>Glide along to the beat,<br>A happy, joyous feat.<br><br>Slide to the left, slide to the right,<br>Smiling faces beaming bright,<br>Create a new and exciting show,<br>Foxtrot is the dance you should know.",
          songs:[{ title:'“Thinking Out Loud” by Ed Sheeran',
                   link:'lp-EO5I60KA'},
                   { title:'“All of Me” by John Legend',
                   link:'ngq5Aw0Q6rQ'}, 
                   { title:'“Fly Me to the Moon” by Frank Sinatra',
                   link:'ZEcqHA7dbwM'},
                   { title:'“I Don’t Want to Miss a Thing” by Aerosmith',
                   link:'JkK8g6FMEXE'},
                   { title:'“You Are the Best Thing” by Ray LaMontagne',
                   link:'pkntWssHboY'},
                   { title:'LOVE - The Swing Cats',
                   link:'DBCA8_RC3So'},
                   { title:'“Unforgettable” by Nat King Cole',
                   link:'-XDAnPvTQFo'},
                   { title:'“The Nearness of You” by Norah Jone',
                   link:'hsczuCzyUs4'},
                   { title:'“I’ve Got You Under My Skin” by Michael Bublé',
                   link:'SMjex7AfTsg'},
                   { title:'“It Had to Be You” by Harry Connick Jr.',
                   link:'_UnQOfPwZfs'},             
                  ]
        },
        {
          name: `Rumba` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'https://youtube.com',
          short:'Short text4.',
          poem:'tralya lya4',
          songs:[{ title:'“Love on the Brain” by Rihanna',
                   link:'nyxKQYWaWOg'},
                   { title:'“Say You Won’t Let Go” by James Arthur',
                   link:'0yW7w8F2TVA'}, 
                   { title:'“Perfect” by Ed Sheeran',
                   link:'kPhpHvnnn0Q'},
                   { title:'“I Will Always Love You” by Whitney Houston',
                   link:'3JWTaaS7LdU'},
                   { title:'“When I Fall in Love” by Nat King Cole',
                   link:'GfAb0gNPy6s'},
                   { title:'“I’m Yours” by Jason Mraz',
                   link:'EkHTsc9PU2A'},
                   { title:'“You Are the Reason” by Calum Scott',
                   link:'ShZ978fBl6Y'},
                   { title:'“I’ll Be There for You” by Bon Jovi',
                   link:'-fj2NRooVRk'}, 
                   { title:'“Just the Way You Are” by Bruno Mars',
                   link:'LjhCEhWiKXk'},
                   { title:'“Have I told you lately” by Rod Stewart',
                   link:'3z-gpMVnnao'},            
                  ]
        },
 
        {
          name: `Viennese Waltz` ,
          img:'/icons/rabbit_hat.svg',
          videoLink:'https://youtube.com',
          short:'Short text4.',
          poem:'tralya lya4',
          songs:[{ title:'“A Thousand Years” by Christina Perri',
                   link:'mk3XycambgI'},
                   { title:'“Can’t Help Falling in Love” by Elvis Presley',
                   link:'vGJTaP6anOU'}, 
                   { title:'',
                   link:''},
                   { title:'',
                   link:''},
                   { title:'',
                   link:''},
                   { title:'',
                   link:''},
                   { title:'',
                   link:''},
                   { title:'',
                   link:''},            
                  ]
        },
              ],
     
  };
  
  export default dataObject;